apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-kubernetes-cicd
  namespace: dev
  labels:
    app: secure-kubernetes-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-kubernetes-cicd
  template:
    metadata:
      labels:
        app: secure-kubernetes-cicd
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: application
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          image: nikhilmaity/secure-kubernetes-cicd:1.0.0
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "1.0.0"